version: '3.1'

services:
  proxy:
    image: nginx
    volumes:
      - ./config/nginx/local/conf.d:/etc/nginx/conf.d
      - ./images:/usr/share/nginx/html:ro
    ports:
      - '80:80'
    depends_on:
      - web
  db:
    image: mongo
    # volumes:
    #   - dbdata:/data/db
  web:
    build: .
    image: daustin/monitor-api
    command: "npm test"
    volumes:
      - ./config/config.json:/var/www/api/config/config.json:ro
      - ./logs:/var/www/api/logs
    depends_on:
      - db

volumes:
  dbdata:
