version: '3.1'

services:
  proxy:
    image: nginx
    volumes:
      - ./config/nginx/local/conf.d:/etc/nginx/conf.d
      - ./images:/usr/share/nginx/html:ro

    ports:
      - '80:80'
  db:
    image: mongo
    volumes:
      - dbdata:/data/db
  web:
    build: .
    image: daustin/monitor-api
    volumes:
      - ./logs:/var/www/api/logs

volumes:
  dbdata:
