version: '3.1'

services:
  proxy:
    image: nginx
    volumes: ./config/conf.d:/etc/nginx/conf.d
  db:
    image: mongo
    volumes:
      - dbdata:/data/db
  web:
    build: .
    image: daustin/monitor-api
    ports:
      - '80:80'

volumes:
  dbdata:
